apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: muq0ukxy6-python
  janus-idp.io/tekton: muq0ukxy6-python
  backstage.io/kubernetes-id: muq0ukxy6-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: muq0ukxy6-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
