apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: muq0ukxy6-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: muq0ukxy6-python 
  name: muq0ukxy6-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: muq0ukxy6-python 
